# Generated by Django 5.0.3 on 2024-08-15 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Ключ')),
                ('text', models.CharField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
                'db_table': 'custom_buttons',
            },
        ),
        migrations.CreateModel(
            name='CustomTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(verbose_name='Ключ')),
                ('text', models.CharField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Текста в боте',
                'db_table': 'custom_texts',
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(verbose_name='Сообщение')),
                ('mailing_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('complete', models.BooleanField(default=False, verbose_name='Отправленно')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылка',
                'db_table': 'mailings',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, verbose_name='Промокод')),
                ('discount', models.BigIntegerField(verbose_name='Скидка в процентах')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promo_code',
            },
        ),
        migrations.CreateModel(
            name='SubjectMatters',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, verbose_name='Название')),
                ('keywords', models.CharField(blank=True, verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Тематика',
                'verbose_name_plural': 'Тематики',
                'db_table': 'subject_matters',
            },
        ),
        migrations.CreateModel(
            name='Tariffs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.BigIntegerField(blank=True, verbose_name='Цена')),
                ('days_open', models.BigIntegerField(blank=True, verbose_name='Кол-во дней доступа')),
                ('title', models.CharField(blank=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'db_table': 'tariffs',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_date', models.DateField(verbose_name='Дата окончания подписки')),
                ('matters', models.ManyToManyField(to='core.subjectmatters', verbose_name='Тематики')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tariffs', verbose_name='Тариф')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'db_table': 'subscription',
            },
        ),
    ]
