# Generated by Django 5.0.3 on 2024-08-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, verbose_name='Путь')),
                ('file_type', models.CharField(blank=True, verbose_name='Тип файла')),
                ('tg_file_id', models.CharField(null=True, verbose_name='Tg id')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'media_files',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждена'),
        ),
        migrations.AddField(
            model_name='bid',
            name='matters',
            field=models.ManyToManyField(to='core.subjectmatters', verbose_name='Тематики'),
        ),
        migrations.AddField(
            model_name='bid',
            name='files',
            field=models.ManyToManyField(to='core.mediafiles', verbose_name='Файлы'),
        ),
    ]
