# Generated by Django 5.0.3 on 2024-08-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mediafiles_bid_is_confirmed_bid_matters_bid_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='text',
            field=models.CharField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
