# Generated by Django 5.0.3 on 2024-08-16 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bid_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.BigIntegerField(null=True, verbose_name='Баланс'),
        ),
        migrations.CreateModel(
            name='ReferralsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='core.users', verbose_name='Реферал')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.users', verbose_name='Реферер')),
            ],
            options={
                'verbose_name': 'Реферал',
                'verbose_name_plural': 'Рефералы',
                'db_table': 'referrals',
            },
        ),
    ]
