# Generated by Django 5.0.3 on 2024-08-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_users_balance_referralstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, verbose_name='Ссылка')),
                ('text', models.CharField(blank=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Картинка')),
                ('video', models.FileField(blank=True, upload_to='', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Полезные материалы',
                'db_table': 'useful_materials',
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='balance',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Баланс'),
        ),
    ]
