# Generated by Django 5.0.3 on 2024-08-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usefulmaterials_alter_users_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='search_switch',
            field=models.BooleanField(default=True, verbose_name='Включен ли поиск'),
        ),
    ]
