# Generated by Django 5.0.3 on 2024-08-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_users_search_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='black_list',
            field=models.ManyToManyField(to='core.subjectmatters', verbose_name='Черный список'),
        ),
    ]
