# Generated by Django 5.0.3 on 2024-08-18 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_users_black_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_link', models.CharField(blank=True, max_length=255, verbose_name='Адрес канала')),
                ('tg_id', models.BigIntegerField(blank=True, null=True, verbose_name='TG id канала')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Канал включен')),
            ],
            options={
                'verbose_name': 'Telegram канал',
                'verbose_name_plural': 'Telegram каналы',
                'db_table': 'channels',
            },
        ),
        migrations.DeleteModel(
            name='Mailings',
        ),
        migrations.AddField(
            model_name='bid',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлена'),
        ),
        migrations.AddField(
            model_name='bid',
            name='mailing_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AddField(
            model_name='bid',
            name='sent_all',
            field=models.BooleanField(default=False, verbose_name='Отправить всем'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='author_username',
            field=models.CharField(null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='bid',
            name='channel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.channels', verbose_name='Канал'),
        ),
    ]
