# Generated by Django 5.0.3 on 2024-08-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_channels_delete_mailings_bid_is_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='author_username',
            field=models.CharField(blank=True, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='mediafiles',
            name='path',
            field=models.FileField(blank=True, upload_to='', verbose_name='Путь'),
        ),
    ]
