# Generated by Django 5.0.3 on 2024-08-22 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_bid_author_username_alter_mediafiles_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='channel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.channels', verbose_name='Канал'),
        ),
    ]
