# Generated by Django 5.0.3 on 2024-09-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_bid_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True)),
                ('user_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'empty_check',
            },
        ),
    ]
