# Generated by Django 5.0.3 on 2024-09-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_emptycheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='trial_subscription_expired',
            field=models.BooleanField(default=False, verbose_name='Пробная подписка потрачена'),
        ),
    ]
