# Generated by Django 5.0.3 on 2024-09-10 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_users_trial_subscription_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tariffs', verbose_name='Тариф'),
        ),
    ]
